using System.ComponentModel;

namespace NetworkAnalyzer.Apps.Settings
{
    internal class GlobalSettings
    {
        // Specifies the root directory used by the Network Analyzer
        public string DataDirectory { get; } = @"C:\Network Analyzer\";

        // Specifies the directory used to store reports generated by the Network Analyzer
        public string ReportDirectory { get; } = $@"C:\Network Analyzer\Reports\";

        // Specifies the directory used to store config and ini files
        public string ConfigDirectory { get; } = $@"C:\Network Analyzer\Config\";

        // Specifies the directory used to store log files
        public string LogDirectory { get; } = $@"C:\Network Analyzer\Reports\";

        // Path to the database file in the Network Analyzer directory
        public string DatabasePath { get; } = $@"C:\Network Analyzer\Config\NetworkAnalyzerDB.db";

        // Path to the database file within the app build path
        public string LocalDatabasePath { get; } = "NetworkAnalyzer.Data.NetworkAnalyzerDB.db";

        // Current build of the application - used to compare to GitHub for notifying the user if a newer version is available
        public string CurrentBuild { get; } = "1.6.1";

        // Release date for the current build of the application - checked against the manifest in GitHub
        public string ReleaseDate { get; } = "11/27/2024";
    }
}