using System.Collections.Concurrent;
using System.ComponentModel;
using System.Net;
using NetworkAnalyzer.Apps.Models;

namespace NetworkAnalyzer.Apps.GlobalClasses
{
    internal static class DataStore
    {
        #region Global
        // Event used to handle property updates for the datastore class
        public static event PropertyChangedEventHandler PropertyChanged;

        // Specifies the root directory used by the Network Analyzer
        public static string DataDirectory { get; } = @"C:\Network Analyzer\";

        // Specifies the directory used to store reports generated by the Network Analyzer
        public static string ReportDirectory { get; } = $@"{DataDirectory}Reports\";

        // Specifies the directory used to store config and ini files
        public static string ConfigDirectory { get; } = $@"{DataDirectory}Config\";

        // Specifies the directory used to store log files
        public static string LogDirectory { get; } = $@"{DataDirectory}Logs\";

        // Path to the database file in the Network Analyzer directory
        public static string DatabasePath { get; } = $@"{ConfigDirectory}NetworkAnalyzerDB.db";

        // Path to the database file within the app build path
        public static string LocalDatabasePath { get; } = "NetworkAnalyzer.Data.NetworkAnalyzerDB.db";

        // Current build of the application - used to compare to GitHub for notifying the user if a newer version is available
        public static string CurrentBuild { get; } = "1.6.1";

        // Release date for the current build of the application - checked against the manifest in GitHub
        public static string ReleaseDate { get; } = "11/27/2024";
        #endregion

        #region IP Scanner Data
        // Store the IP Bounds for the current session
        public static ConcurrentBag<IPv4Info> ActiveSubnets = new();

        // Represents the total amount of IP Addresses available to scan in the provided range
        private static int _totalSizeOfSubnetToScan;
        public static int TotalSizeOfSubnetToScan
        {
            get => _totalSizeOfSubnetToScan;
            set
            {
                if (_totalSizeOfSubnetToScan != value)
                {
                    _totalSizeOfSubnetToScan = value;

                    OnStaticPropertyChanged(nameof(TotalSizeOfSubnetToScan));
                }
            }
        }

        // Represents the total amount of IP Addresses which have been successfully pinged
        private static int _totalActiveIPAddresses;
        public static int TotalActiveIPAddresses
        {
            get => _totalActiveIPAddresses;
            set
            {
                if (_totalActiveIPAddresses != value)
                {
                    _totalActiveIPAddresses = value;

                    OnStaticPropertyChanged(nameof(TotalActiveIPAddresses));
                }
            }
        }

        // Represents the total amount of IP Addresses which have failed to respond to pings
        private static int _totalInactiveIPAddresses;
        public static int TotalInactiveIPAddresses
        {
            get => _totalInactiveIPAddresses;
            set
            {
                if (_totalInactiveIPAddresses != value)
                {
                    _totalInactiveIPAddresses = value;

                    OnStaticPropertyChanged(nameof(TotalInactiveIPAddresses));
                }
            }
        }

        // Stores the duration of the scan
        public static string TotalScanDuration { get; set; } = string.Empty;

        // Datetime the scan was performed
        public static string DateScanWasPerformed { get; set; } = string.Empty;

        // Report number for the currently running IP Scanner session
        public static string IPScannerReportID { get; set; } = string.Empty;

        // Report type for the currently running IP Scanner session
        public static ReportType IPScannerReportType { get; set; } = ReportType.ICMP;
        #endregion

        #region Reports Data
        // Store list of all reports in the ReportDirectory
        public static ConcurrentBag<ReportExplorerData> ReportsData = new();
        #endregion Reports Data

        #region Private Methods
        public static void OnStaticPropertyChanged(string propertyName)
        {
            PropertyChanged?.Invoke(null, new PropertyChangedEventArgs(propertyName));
        }
        #endregion
    }
}